### ISSUE TITLE
Problem with seeking in long network source videos

### ISSUE THREAD

**Issue by chaeMil** [zezo357/video_player_media_kit#4]
First, thanks for the awesome work!

The problem arises when you play long network video. Seeking in the video is not working it just continues to play. 

`Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E772610a darwin-x64, locale en-GB)`

**Comment by abdelaziz-mahdy** [comment]
> First, thanks for the awesome work!
> 
> The problem arises when you play long network video. Seeking in the video is not working it just continues to play. 
> 
> `Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E772610a darwin-x64, locale en-GB)`

Does the issue got closed by mistake? Or it was fixed?

Does it  happen in the example code?

**Comment by chaeMil** [comment]
Sorry wrong package 😅

**Comment by abdelaziz-mahdy** [comment]
> Sorry wrong package 😅

Okay, but does it happen in my package? 😂

Just to fix it 😀
