### ISSUE TITLE
Error passing from version 0.0.9 to 0.0.10

### ISSUE THREAD

**Issue by BrunoC96** [zezo357/video_player_media_kit#5]
Hi,

I have this log file, after I upgrade video player media kit from `0.0.9` to `0.0.10`, before was working fine.

`../../../.pub-cache/hosted/pub.dev/video_player_media_kit-0.0.10/lib/video_player_media_kit_platform/video_player_media_kit_platform_ffi.dart:80:45: Error: Member not found: 'VideoController.create'.
    controllers[id] = await VideoController.create(player);
                                            ^^^^^^
../../../.pub-cache/hosted/pub.dev/video_player_media_kit-0.0.10/lib/video_player_media_kit_platform/video_player_media_kit_platform_ffi.dart:264:29: Error: The method 'dispose' isn't defined for the class 'VideoController'.
 - 'VideoController' is from 'package:media_kit_video/src/video_controller/video_controller.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.10/lib/src/video_controller/video_controller.dart').
Try correcting the name to the name of an existing method, or defining a method named 'dispose'.
    controllers[textureId]!.dispose();`

**Comment by abdelaziz-mahdy** [comment]
Yes media_kit released an update yesterday, I will update to it today hopefully

**Comment by BrunoC96** [comment]
Ok so, need to wait the new update for this version to work, right?

**Comment by abdelaziz-mahdy** [comment]
Or use a media_kit override with 0.0.7 as a version

**Comment by BrunoC96** [comment]
I try to override:


`dependency:`
`  ...`
`dependency_overrides:`
`  media_kit_video: 0.0.7`


But I get this error log:

`../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.7/lib/src/video_controller_android.dart:22:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/media_kit-0.0.8/lib/src/libmpv/core/native_library.dart': No such file or directory
import 'package:media_kit/src/libmpv/core/native_library.dart';
       ^
../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.7/lib/src/video_controller_android.dart:100:5: Error: Undefined name 'NativeLibrary'.
    NativeLibrary.ensureInitialized();
    ^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.7/lib/src/video_controller_android.dart:101:41: Error: Undefined name 'NativeLibrary'.
    final mpv = MPV(DynamicLibrary.open(NativeLibrary.path));
                                        ^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.7/lib/src/video_controller_android.dart:156:5: Error: The getter 'NativeLibrary' isn't defined for the class 'VideoControllerAndroid'.
 - 'VideoControllerAndroid' is from 'package:media_kit_video/src/video_controller_android.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.7/lib/src/video_controller_android.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'NativeLibrary'.
    NativeLibrary.ensureInitialized();
    ^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.7/lib/src/video_controller_android.dart:157:41: Error: The getter 'NativeLibrary' isn't defined for the class 'VideoControllerAndroid'.
 - 'VideoControllerAndroid' is from 'package:media_kit_video/src/video_controller_android.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.7/lib/src/video_controller_android.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'NativeLibrary'.
    final mpv = MPV(DynamicLibrary.open(NativeLibrary.path));`

where it ask for NativeLibrary.

**Comment by BrunoC96** [comment]
My bad,
for who have the same problem, in the meantime you need both `media_kit` and `media_kit_video` to `0.0.7`

like this:

`dependency`
`    ...`
`dependency_overrides:`
`   media_kit: 0.0.7`
`   media_kit_video: 0.0.7`

**Comment by abdelaziz-mahdy** [comment]
> My bad,
> for who have the same problem, in the meantime you need both `media_kit` and `media_kit_video` to `0.0.7`
> 
> like this:
> 
> `dependency`
> `    ...`
> `dependency_overrides:`
> `   media_kit: 0.0.7`
> `   media_kit_video: 0.0.7`

Yes I forgot that, anyway I will fix it and let you know here

**Comment by abdelaziz-mahdy** [comment]
fixed in new release
