### ISSUE TITLE
 Compilation to web platform reported an error

### ISSUE THREAD

**Issue by AnonymHK** [zezo357/video_player_media_kit#6]
Compilation to web platform reported an error, 

video_player_media_kit-0.0.21/lib/video_player_media_kit_platform/video_player_media_kit_platform_web.dart:88:45: Error: Type 'VideoPlayerWebOptions' not found.
  Future<void> setWebOptions(int textureId, VideoPlayerWebOptions options) {
                                            ^^^^^^^^^^^^^^^^^^^^^

Failed to compile application.

**Comment by AnonymHK** [comment]
Flutter version 3.10.6 
Dart version 3.0.6
DevTools version 2.23.1

**Comment by abdelaziz-mahdy** [comment]
what version of the video_player are you using?
it should be working, since i fixed that error a while ago
can you test on last one?

**Comment by abdelaziz-mahdy** [comment]
i am rerunning the github actions, maybe video_player got updated and is the reason for this error

**Comment by AnonymHK** [comment]
I am using flutter_meedu_videoplayer: ^ 4.2.21 The latest version, I have reviewed the yaml configuration file, video  The version of player should be 2.7.0

**Comment by abdelaziz-mahdy** [comment]
>  I am using flutter_meedu_videoplayer: ^ 4.2.21 The latest version, I have reviewed the yaml configuration file, video  The version of player should be 2.7.0 

Very weird, can you share your pubspec.

**Comment by AnonymHK** [comment]
I don't know what's going on, Flutter_ Meedu_ Videoplayer_ The example runs normally, and only Flutter is referenced in my project_ Meedu_ Videoplayer, there are no other video related components, and the non web environment is normal. This error occurred on the web!

**Comment by AnonymHK** [comment]
Can you tell me where this problem is caused so that I can investigate it?

**Comment by abdelaziz-mahdy** [comment]
> Can you tell me where this problem is caused so that I can investigate it?

the problem is that video_player plaform interface got updated and i am using latest one 

but but , can you do flutter pub upgrade and try again?

**Comment by abdelaziz-mahdy** [comment]
video_player_platform_interface: ^6.0.1
is in this package pubspec, but it should be 6.2.0

so let me know if flutter pub upgrade fixed the problem

**Comment by AnonymHK** [comment]
video_player 2.7.0
> video_player_android 2.4.9 (was 2.4.6)
> video_player_avfoundation 2.4.9 (was 2.4.5)
  video_player_media_kit 0.0.21
> video_player_platform_interface 6.2.0 (was 6.1.0)
  video_player_web 2.0.16
  
   The problem has been resolved after the Flutter pub, it seems to be a cache issue~!
